### PR TITLE
[utils] Get the files hieararcy.yml and projects-repos.yml from a GitHub

### PR DESCRIPTION
**Pull request by zhquan**

### CODE REVIEW

**Comment by sanacl** [comment]
By reading the log of the commit I don't understand what it does. Please writter a more descriptive commit log. Remember: https://en.wikibooks.org/wiki/Git/Introduction#Good_commit_messages

**Comment by acs** [comment]
@zhquan is this PR valid yet? Should we review it?

**Comment by zhquan** [comment]
I don't know.
@sanacl is this PR still valid?

**Comment by jgbarah** [comment]
@acs @sancl if you want, I can test and interact with @zhquan to learn about how valid this (or something similar) may be. As I see it, it was a first effort for getting a projects.json (or similar) file for a GitHub organization. I think I'm familiar with the matter.

**Comment by acs** [comment]
I would not invest effort into this PR. Bestiary is pretty close to be used for doing exactly that.

**Comment by jgbarah** [comment]
Where can I find bestiary?

**Comment by acs** [comment]
The fork in which I am working is at: https://github.com/acs/bestiary

The specific code to build projects JSON files to be used as input for mordred is at:

https://github.com/acs/bestiary/tree/pathfinder

**Comment by acs** [comment]
@zhquan I am closing this issue because Bestiary will change how the things are done here, and also, because mordred has evolved and supports now some of then features in this PR. If you think we need to work more on it, please, reopen the ticket.

Thanks for your contribution!

**Pull request closed without merging**
