### PR TITLE
ability to setup and configure RotatingFileHandler for file logging

### PR DESCRIPTION
**Pull request by trbs**
Add the ability to setup and configure rotating log files via RotatingFileHandler.

If wanted this patch could be extended for supporting other file handlers as well.
Or possibly disabling file handlers and only logging to console (which might be good for some container setups)

### CODE REVIEW

**Comment by acs** [comment]
@trbs I am going to review all this work asap. I am a bit overloaded past weeks. Thank you very much for your work. I promise I will invest time in reviewing it! Logs rotating is a critical feature for us in production, and any improvement will help!

**Comment by trbs** [comment]
@acs great. Right now the PR is polluted with other fixes like the last commit resetting IDENTITIES_TASKS_ON when an error happens in sortinghat. For me that was mysql network error, which causes Mordred to "deadlock". (although i'm not sure if the driver recovers from it since I never use MySQL)

Anyways please see which changes you want to merge and I can create new clean PR's for them.

**Comment by acs** [comment]
@trbs it is better to go step by step in the PRs. Each feature in a specific PR which can be merged without issues with master.

Could you clean the PR so it merges with merges and it is only related to a specific feature? For example, the rotating of logs. The other features must be in new PRs.

Thanks @trbs !

**Comment by trbs** [comment]
@acs opened https://github.com/grimoirelab/mordred/pull/64 and https://github.com/grimoirelab/mordred/pull/65 which should be clean patches on top of Mordred master.

**Pull request closed without merging**
