### PR TITLE
get the repos for a Github organization

### PR DESCRIPTION
**Pull request by zhquan**

### CODE REVIEW

**Comment by sanacl** [comment]
User should be allowed to specify a name both for hierarchy and project-repos file.

**Comment by sanacl** [comment]
`luis@hogaza ~/repos/mordred/utils ±zhquan-yml_projectsfile⚡ » python3 github2projectsfiles.py h.yml p.yml metricsgrimoire
Traceback (most recent call last):
  File "github2projectsfiles.py", line 233, in <module>
    projects_repos = add_projects(repos, projects_repos, org)
  File "github2projectsfiles.py", line 178, in add_projects
    name = repo.split(org+"/")[1].split(".git")[0]
IndexError: list index out of range
`

Please fix also this. The changes should be included in a single commit. So group them before submitting again the PR

**Comment by sanacl** [comment]
It works, but the parameters are misleading.

```
luis@hogaza ~/repos/mordred/utils ±master⚡ » python3 github2projectsfiles.py -h                                 2 ↵
usage: github2projectsfiles.py [-h] [-p PARENT] [-b BLACKLIST] [-r RENAME]
                               hierarchy projects_repos org

Get the repos for a Github organization and return hierarchy.yml and porjects-repos.yml

positional arguments:
  hierarchy             hierarchy.yml
  projects_repos        projects_repos.yml
  org                   Github organization
```

The first two positional arguments are wrong. They should be optional, something like:
- "--h" for the hierarchy file, with a default value like "hierarchy.yml"
- "--r" for the project repos file, with a default value like "project_repos.yml"

Next actions:
- modify this and squash it in a single commit
- ensure we are not getting repository forks

**Comment by zhquan** [comment]
I close this, but I will open other PR with all the changes

**Pull request closed without merging**
